config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"

  get "invitations", to: "invitations#new_invite_list"
  post "invitations", to: "invitations#create"
  delete "invitations", to: "invitations#destroy"

  post "attendances/join", to: "attendances#join"
  delete "attendances/leave", to: "attendances#leave"
  get "my_events", to: "users#show"

  devise_for :users

  get "events", to: "events#index"
  get "events/new", to: "events#new"
  post "events", to: "events#create"
  get "events/:id", to: "events#show", as: "event"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user, foreign_key: :attendee_id
  belongs_to :event, foreign_key: :attended_event_id
end

app/models/attending.rb
class Attending < ApplicationRecord
  belongs_to :user, foreign_key: :attendee_id
  belongs_to :event, foreign_key: :attended_event_id
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }

  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: "attended_event_id"
  has_many :attendees, through: :attendances, foreign_key: "attended_event_id", source: :user

  has_many :invitations, foreign_key: "invited_to_id"
  has_many :invitees, through: :invitations, source: :user
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user, foreign_key: "invitee_id"
  belongs_to :event, foreign_key: "invited_to_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendances, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendances, foreign_key: "attendee_id", source: :event

  has_many :invitations, foreign_key: "invitee_id"
  has_many :invited_tos, through: :invitations, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name ])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def join
    @event = Event.find(params[:event_id])
    @attendance = current_user.attendances.new(attended_event_id: @event.id)
    if @attendance.save
      if current_user.invitations.exists?(invited_to_id: @event.id)
        current_user.invitations.find_by(invited_to_id: @event.id).delete
      end
      redirect_to my_events_path, notice: "You're on the list. See you at #{@event.location}!"
    else
      render @event, notice: "Sorry, there was an error!"
    end
  end

  def leave
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find(params[:attendance_id])
    @attendance.destroy
    redirect_to my_events_path, notice: "You have been successfully removed from the list!"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :event_params, only: [ :create ]
  before_action :authenticate_user!, only: [ :show, :new, :create ]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      current_user.attendances.create(attended_event_id: @event.id)
      redirect_to @event, notice: "Event succesfully created!" 
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.expect(event: [ :location, :date ])
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!
  def create
    @event_id = params[:event_id]
    puts @event_id
    @users = params[:invitee_ids]
    @users.each do |user|
      next if user == ""  # First entry in array returned by form is always an empty String
      @invitation = Invitation.new(invited_to_id: @event_id, invitee_id: user)
      @invitation.save
    end
    redirect_to my_events_path, notice: "Invitations sent!"
  end

  def new_invite_list
    @event = Event.find(params[:event_id])
    @users = []
    User.all.each do |user|
      if user.attended_events.exists?(@event.id)
        next
      else
        @users << user
      end
    end
    @invitation = Invitation.new
  end

  def destroy
    @user = current_user
    @event_id = params[:event_id]
    @invitation = Invitation.find_by(invitee_id: @user.id, invited_to_id: @event_id)
    @invitation.destroy
    redirect_to my_events_path, notice: "Invitation declined!"
  end

  private
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/join.html.erb
<h1>Attendances#join</h1>
<p>Find me in app/views/attendances/join.html.erb</p>

app/views/attendances/leave.html.erb
<h1>Attendances#leave</h1>
<p>Find me in app/views/attendances/leave.html.erb</p>

app/views/events/_attendees.html.erb
<p><strong>Guest List:</strong></p>
<% @event.attendees.each do |attendee| %>
  <%= attendee.first_name + " " + attendee.last_name %> <br>
<% end %>

app/views/events/_join_or_leave.html.erb
<% if current_user.attended_events.exists?(@event.id) %>
  <% if @event.creator_id == current_user.id %>
    <%= button_to "Send Invitations", invitations_path, params: { event_id: @event.id }, method: :get %>
  <% end %>
  <%= button_to "Leave", attendances_leave_path, params: {attendance_id: current_user.attendances.find_by(attended_event_id: @event.id).id, event_id: @event.id}, method: :delete %>
<% elsif current_user.invited_tos.exists?(@event.id) %>
  <%= button_to "Accept", attendances_join_path, params: { event_id: @event.id }, method: :post %>
  <%= button_to "Decline", invitations_path, params: { event_id: @event.id }, method: :delete %>
<% end %>

app/views/events/index.html.erb
<h1 style="text-align:center">Events</h1>
<div class="page_container">
  <div class="events_container">
    <h2>Past</h2>
    <% @events.past.each do |event| %>
      <div class = "event">
        <div><strong>Location: </strong><%= event.location %></div>
        <p><strong>Date:</strong> <%= event.date %></p>
        <%= link_to "Event Details", event %>
      </div>
    <% end %>
  </div>
  <div class="events_container">
    <h2>Upcoming</h2>
    <% @events.upcoming.each do |event| %>
      <div class = "event">
        <div><strong>Location: </strong><%= event.location %></div>
        <p><strong>Date:</strong> <%= event.date %></p>
        <%= link_to "Event Details", event %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Create a new event</h1>
<%= form_with model: @event do |form| %>
  <% if @event.errors.any? %>
    <p><%= @event.errors.first.full_message %></p>
  <% end %>
  <div>
    <%= form.label :location, "Location" %> <br>
    <%= form.text_field :location %>
  </div>
  <div>
    <%= form.label :date, "Date" %> <br>
    <%= form.datetime_field :date %>
  </div>
  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h1 style="text-align:center">Event Details</h1>
<div class="page_container">
  <div class="events_container">
    <div class="event">
      <p><strong>Location:</strong> <%= @event.location %></p>
      <p><strong>Date:</strong> <%= @event.date %></p>
      <p><strong>Creator:</strong> <%= @event.creator.first_name + " " + @event.creator.last_name %></p>
      <%= render "attendees" %>
    </div>
    <%= render "join_or_leave" %>
  </div>
</div>

app/views/invitations/invite.html.erb
<h1>Invitations#invite</h1>
<p>Find me in app/views/invitations/invite.html.erb</p>

app/views/invitations/new_invite_list.html.erb
<h3 style="text-align:center">Send Invites</h3>

<div class="page_container">
  <div class="events_container">
    <div class="event">
      <p><strong>Location:</strong> <%= @event.location %></p>
      <p><strong>Date:</strong> <%= @event.date %></p>
      <p><strong>Creator:</strong> <%= @event.creator.first_name + " " + @event.creator.last_name %></p>
      <%= render "events/attendees" %>
    </div>
  </div>
  <%= form_with url: invitations_path, method: :post do |form| %>
    <div class="events_container">
      <%= form.hidden_field :event_id, value: @event.id %>
      <%= form.label :invitee_ids, "Create a guest list:" %>
      <div class="event">
        <%= form.collection_check_boxes(:invitee_ids, @users, :id, :first_name) do |b| %>
          <%= b.label {b.check_box + b.text} %>
        <% end %>
      </div>
      <div style="text-align:center"><%= form.submit "Send invites"%></div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/links_header" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/shared/_links_header.html.erb
<div class="nav_bar">
  <%= link_to "Home", root_path %>
  <%= link_to "My Events", my_events_path %>
  <% if user_signed_in? %>
    <%= link_to "Create Event", events_new_path %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to "Sign In", new_user_session_path, method: :get %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 style="text-align:center"><%= @user.first_name + " " + @user.last_name %>'s Events</h1>
<div class="page_container">
    <div class="events_container">
      <h2>Hosted</h2>
      <% @user.events.each do |event| %>
        <div class="event">
          <p><strong>Location:</strong> <%= event.location %></p>
          <p><strong>Date:</strong> <%= event.date %></p>
          <div class="event_links">
            <%= link_to "Details", event %>
            <%= button_to "Send Invitations", invitations_path, params: { event_id: event.id, }, method: :get %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="events_container">
      <h2>Attending</h2>
      <% upcoming = @user.attended_events.where("date > ?", Time.now) %>
      <% past = @user.attended_events.where("date < ?", Time.now) %>
      <h3>Upcoming</h3>
      <% upcoming.each do |event| %>
        <div class="event">
          <p><strong>Location:</strong> <%= event.location %></p>
          <p><strong>Date:</strong> <%= event.date %></p>
          <%= link_to "Details", event %>
        </div>
      <% end %>
      <h3>Past</h3>
      <% past.each do |event| %>
        <div class="event">
          <p><strong>Location:</strong> <%= event.location %></p>
          <p><strong>Date:</strong> <%= event.date %></p>
          <%= link_to "Details", event %>
        </div>
      <% end %>
    </div>
  <div class="events_container">
    <h2>Invitations</h2>
    <% @user.invitations.each do |invite| %>
      <% @event = Event.find(invite.invited_to_id) %>
      <div class="event">
        <p><strong>Location: </strong><%= @event.location %></p>
        <p><strong>Date: </strong><%= @event.date %></p>
        <%= link_to "Details", @event %>
      </div>
    <% end %>
  </div>
</div>